name: Update File Index

on:
    push:
      branches: [ main ]

jobs:
  update:
    name: Update File Index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run python script
        run: |
          cd .github
          python update.py
