name: Update Repository

on:
  push:
    branches: [main]

jobs:
  update:
    name: Update Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate files
        run: |
          python update.py

      - name: Commit changes
        run: |
          git config user.name "HuYo-OS"
          git config user.email "HuYo-OS@outlook.com"
          git add -A
          git commit -m "Update repository"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
